name: CI Discord
on:
 workflow_run:
   workflows: ["CI build"]
   types:
     - completed
jobs:
  discord:
    runs-on: ubuntu-latest
    steps:
      - name: Discord notification
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        uses: sarisia/actions-status-discord@v1
        if: always()
        with:
          description: 'Le projet SpringBoot API a été build avec succès'